# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

trajectory_execution:
  allowed_execution_duration_scaling: 1.2
  allowed_goal_duration_margin: 0.5
  allowed_start_tolerance: 0.01
  execution_duration_monitoring: false # May lead to unexpectedly aborted goals with moprim_from_traj_controller

moveit_simple_controller_manager:
  controller_names:
    - position_trajectory_controller
    - motion_primitive_from_trajectory_controller

  position_trajectory_controller:
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: false
    joints:
        - joint_a1
        - joint_a2
        - joint_a3
        - joint_a4
        - joint_a5
        - joint_a6
  motion_primitive_from_trajectory_controller:
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
        - joint_a1
        - joint_a2
        - joint_a3
        - joint_a4
        - joint_a5
        - joint_a6